export const CHANGE_LANGTO = 'CHANGE_LANGTO';
export const CHANGE_LANGFROM = 'CHANGE_LANGFROM';
export const REQUEST_LANGS = 'REQUEST_LANGS';
export const RECEIVE_LANGS = 'RECEIVE_LANGS';
export const ERROR_LANGS = 'ERROR_LANGS';
export const REQUEST_TRANSLATE = 'REQUEST_TRANSLATE';
export const RECEIVE_TRANSLATE = 'RECEIVE_TRANSLATE';
export const ERROR_TRANSLATE = 'ERROR_TRANSLATE';